### ISSUE TITLE
Find good water material

### ISSUE THREAD

**Issue by lzwdgc** [aimrebirth/Polygon4#4]

**Comment by GranMinigun** [comment]
Here's interesting project: https://forums.unrealengine.com/community/work-in-progress/17331-community-project-wip-weather-ocean-water-shader

**Comment by ghost** [comment]
Found a very good [BP/MAT water system](https://youtu.be/pX82z77TZc4) that is constantly improved by the [author](https://www.youtube.com/channel/UC4ZQRa8HaOkGPZuEuiWKd2w/about). It's been already implemented.
